name: NASA Project CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v2
      -name: uses Node Version 21
      -uses: actions/setup-node@v2
      with:
        node-version: '21'
      -run: npm install
      -run : npm run build --prefix Client

